/**
 * ${config.name}
 * 
 * Generated by BOSS CLI
 */

export function main(): void {
  console.log('Hello from ${config.name}!');
}

// Uncomment to run when this file is executed directly
// main();

